[[redirects]]
  from = "/api/*"
  to = "https://clothing-store-ct6i.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { 
    "Access-Control-Allow-Origin" = "https://style-loom.netlify.app",
    "Access-Control-Allow-Credentials" = "true"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
