export const items: string[] = [
  "tank-top",
  "long-sleeve t-shirt",
  "crop-top",
  "v-neck shirt",
  "muscle shirt",
  "gowns",
  "handbags",
  "purses",
  "clutchbags",
  "slides",
  "caps",
  "durags",
  "hoodies",
  "sweaters",
  "cardigans",
  "jeans",
  "shorts",
  "skirts",
  "blouses",
  "jackets",
  "belts",
  "scarves",
  "sunglasses",
  "watches",
  "earrings",
  "necklaces",
  "bracelets",
  "rings",
  "boots",
  "sandals",
  "sneakers",
  "formal shoes",
  "casual shoes",
  "suits",
  "blazers",
  "overalls",
  "leggings",
  "jumpsuits",
  "rompers",
  "turtlenecks",
  "polo shirts",
  "sweatpants",
  "track suits",
  "swimwear",
  "athletic wear",
];
